### ISSUE TITLE
dicom2nifti not in package requirements

### ISSUE THREAD

**Issue by njneeteson** [Bonelab/Ogo#17]
creating issue to remember and fix later. 

Tried to run "ogodicom2nii" and got the following error:
```
(ogo) Ogo % ogodcm2nii
Traceback (most recent call last):
  File "/Users/nathanneeteson/opt/anaconda3/envs/ogo/bin/ogodcm2nii", line 6, in <module>
    from ogo.cli.dcm2nii import main
  File "/Users/nathanneeteson/Projects/active_development/Ogo/ogo/cli/dcm2nii.py", line 14, in <module>
    import dicom2nifti
ModuleNotFoundError: No module named 'dicom2nifti'
```

**Comment by stevenkboyd** [comment]
Added it to the installation instructions in README.md
